"""esquema inicial: clients, source_files, delivery_notes, delivery_note_items

Revision ID: 807c07f3b277
Revises: 
Create Date: 2026-08-05 13:28:31.120297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '807c07f3b277'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('client_number', sa.String(length=50), nullable=False),
    sa.Column('client_name', sa.Text(), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('drive_folder_id', sa.Text(), nullable=True),
    sa.Column('drive_folder_link', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('client_number')
    )
    op.create_table('source_files',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('drive_file_id', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=False),
    sa.Column('original_drive_link', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('detected_remitos', sa.Integer(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('drive_file_id')
    )
    op.create_table('delivery_notes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_file_id', sa.UUID(), nullable=False),
    sa.Column('client_id', sa.UUID(), nullable=True),
    sa.Column('document_number', sa.String(length=100), nullable=True),
    sa.Column('document_date', sa.Date(), nullable=True),
    sa.Column('document_time', sa.Time(), nullable=True),
    sa.Column('client_number', sa.String(length=50), nullable=True),
    sa.Column('client_name', sa.Text(), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('locality', sa.Text(), nullable=True),
    sa.Column('supplier_name', sa.Text(), nullable=True),
    sa.Column('seller_name', sa.Text(), nullable=True),
    sa.Column('tax_id', sa.Text(), nullable=True),
    sa.Column('payment_condition', sa.Text(), nullable=True),
    sa.Column('work_reference', sa.Text(), nullable=True),
    sa.Column('drive_file_id', sa.Text(), nullable=True),
    sa.Column('drive_file_link', sa.Text(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('crop_index', sa.Integer(), nullable=True),
    sa.Column('signed', sa.Boolean(), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('raw_ocr_text', sa.Text(), nullable=True),
    sa.Column('extraction_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['source_file_id'], ['source_files.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_delivery_notes_client_document', 'delivery_notes', ['client_number', 'document_number'], unique=False)
    op.create_table('delivery_note_items',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('delivery_note_id', sa.UUID(), nullable=False),
    sa.Column('line_number', sa.Integer(), nullable=True),
    sa.Column('product_code', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=3), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('brand', sa.Text(), nullable=True),
    sa.Column('confidence', sa.Numeric(precision=5, scale=4), nullable=True),
    sa.ForeignKeyConstraint(['delivery_note_id'], ['delivery_notes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('delivery_note_items')
    op.drop_index('ix_delivery_notes_client_document', table_name='delivery_notes')
    op.drop_table('delivery_notes')
    op.drop_table('source_files')
    op.drop_table('clients')
    # ### end Alembic commands ###
